### ISSUE TITLE
Create a standalone .exe for ComUI (the GUI that wraps the main comcom script)

### ISSUE THREAD

**Issue by bajuwa** [bajuwa/ComicCompiler#18]
**Options to Investigate**
* py2exe : https://www.py2exe.org/index.cgi/Tutorial
* Can imagemagick be included in the exe?
     * Can be deferred if not (since imagemagick is self installing)
* ~~is the sh.exe standalone or compatible with Python imports?~~
     * It's not standalone, and python can run command line scripts but would still need sh.exe
* Rewrite the script in python....?
     * This would replace the need to install a shell compatible window with the python installation to run on command line instead
     * Can create a separate GUI that would then just call the rewritten python script

**Comment by as280093** [comment]
Making A standalone exe is better then the current as in current user requires to install 40 MB of Github Git Application of 100+Mb of Ubuntu Application
plus most of the user doesn't know how to setup path of comcom 
here is a wireframe on who application might look if made as application still not a complete idea 
![image](https://user-images.githubusercontent.com/25240839/77303319-c6ca2280-6d18-11ea-9dfd-86de9112cf82.png)

**Comment by as280093** [comment]
the more complex idea for
![image](https://cdn.discordapp.com/attachments/691973179907899472/692078153937715300/cs.jpg)

**Comment by bajuwa** [comment]
@as280093 please put that in issue #31 as this issue is just for getting the ComUI project in exe form (not the actual design/creation of the GUI itself)
