### ISSUE TITLE
Create a simple GUI

### ISSUE THREAD

**Issue by bajuwa** [bajuwa/ComicCompiler#31]
**Requirements**
* All command line arguments should be represented as options in the GUI
* The command line output should be visible (MVP = just open the terminal separately if that's easier)

**Comment by bajuwa** [comment]
Here's a suggestion for what one of the eventual GUI designs might look like:

> Making A standalone exe is better then the current as in current user requires to install 40 MB of Github Git Application of 100+Mb of Ubuntu Application
> plus most of the user doesn't know how to setup path of comcom 
> here is a wireframe on who application might look if made as the application still not a complete idea 
> 
> ![image](https://user-images.githubusercontent.com/25240839/77304878-1c073380-6d1b-11ea-83ca-b861eae69041.png)

_Originally posted by @as280093 in https://github.com/bajuwa/ComicCompiler/issues/18#issuecomment-602487435_

**Comment by as280093** [comment]
the more complex idea for
![image](https://cdn.discordapp.com/attachments/691973179907899472/692078153937715300/cs.jpg)
